<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>df0e450b-2aa8-4dc5-8c87-cea86f8769eb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Agents\**" />
    <Content Remove="Agents\**" />
    <EmbeddedResource Remove="Agents\**" />
    <None Remove="Agents\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.10.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.28.0" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.22.0" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.22.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.15" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.11.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" Version="1.76.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" Version="1.76.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Onnx" Version="1.76.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.76.0" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
  </ItemGroup>

</Project>
